blueprint:
  name: Family Light — Orange Hour, then Red & Off
  description: >
    At a set time, change light.family_light from red to orange for the specified duration.
    After the duration, set it back to red and then turn it off.
  domain: automation
  input:
    start_time:
      name: Start time
      selector:
        time: {}

    duration:
      name: Orange duration
      description: How long to stay orange before returning to red and turning off
      default: 01:00:00
      selector:
        duration: {}

    brightness_pct:
      name: Brightness (%)
      default: 100
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
          mode: slider

    transition_secs:
      name: Transition (seconds)
      default: 1
      selector:
        number:
          min: 0
          max: 10
          step: 1
          unit_of_measurement: s
          mode: slider

mode: restart

trigger:
  - platform: time
    at: !input start_time

condition: []

action:
  - service: light.turn_on
    target:
      entity_id: light.family_light
    data:
      hs_color: [30, 100]      # orange
      brightness_pct: !input brightness_pct
      transition: !input transition_secs

  - delay: !input duration

  - service: light.turn_on
    target:
      entity_id: light.family_light
    data:
      hs_color: [0, 100]       # red
      brightness_pct: !input brightness_pct
      transition: !input transition_secs

  - service: light.turn_off
    target:
      entity_id: light.family_light
    data:
      transition: !input transition_secs
