blueprint:
  name: Family Light — Fade to Light Orange & Stay On
  description: >
    At a set time, fade light.genio_pixel_rgb_led_bar_light (Ambient Light bar)
    to a light orange at the chosen brightness and leave it on.
  domain: automation
  input:
    start_time:
      name: Start time
      selector:
        time: {}

    brightness_orange_pct:
      name: Orange brightness (%)
      description: Brightness for the light orange state
      default: 15
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
          mode: slider

    transition_secs:
      name: Transition (seconds)
      description: Fade time when changing to light orange
      default: 1
      selector:
        number:
          min: 0
          max: 10
          step: 1
          unit_of_measurement: s
          mode: slider

mode: restart

trigger:
  - platform: time
    at: !input start_time

condition: []

action:
  # Fade to light orange and leave the light on
  - service: light.turn_on
    target:
      entity_id: light.genio_pixel_rgb_led_bar_light
    data:
      hs_color: [30, 75]    # light orange
      brightness_pct: !input brightness_orange_pct
      transition: !input transition_secs
