blueprint:
  name: Kids Night Light — 5-Minute Step Ramp to Green, Hold, Back to Red & Off (Tuya-friendly)
  description: >
    At the set time (default 06:05), step the light from red (1%) to green (100%) over 5 minutes
    using minute-by-minute colour/brightness changes (no transitions). Hold green for the duration
    (default 2h), then return to red (1%), wait a short settle delay (default 5s), and turn off.
    Palette: Red → Red-Orange (h=20) → Yellow (60) → Yellow-Green (90) → Green (120), sat=100.

  domain: automation

  input:
    target_light:
      name: Target light
      description: The night light to control
      selector:
        entity:
          domain: light
      default: light.kids_night_light

    start_time:
      name: Start time
      selector:
        time: {}
      default: "06:05:00"

    minute_step_secs:
      name: Seconds per step
      description: How long to wait between each minute-by-minute colour step
      default: 60
      selector:
        number:
          min: 10
          max: 120
          step: 5
          unit_of_measurement: s
          mode: slider

    green_hold_duration:
      name: Green hold duration
      description: How long to stay green before returning to red and turning off
      default: "02:00:00"
      selector:
        duration: {}

    red_brightness_pct:
      name: Red brightness (%)
      description: Brightness while red (before/after)
      default: 1
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
          mode: slider

    green_brightness_pct:
      name: Green brightness (%)
      description: Brightness while green at the end of the ramp
      default: 100
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
          mode: slider

    orange_hue_deg:
      name: Red-orange hue (degrees)
      description: Hue for the red-orange step (20 = red-orange, 30 = golden orange)
      default: 20
      selector:
        number:
          min: 0
          max: 360
          step: 1
          unit_of_measurement: "°"
          mode: slider

    saturation_pct:
      name: Saturation (%)
      description: Saturation for all steps
      default: 100
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
          mode: slider

    post_red_settle_secs:
      name: Settle delay after returning to red (seconds)
      description: Wait this long after switching back to red before turning off
      default: 5
      selector:
        number:
          min: 0
          max: 30
          step: 1
          unit_of_measurement: s
          mode: slider

mode: restart

trigger:
  - platform: time
    at: !input start_time

condition: []

action:
  # Minute 0 — ensure starting state: Red @ 1%
  - service: light.turn_on
    target:
      entity_id: !input target_light
    data:
      hs_color:
        - 0
        - !input saturation_pct
      brightness_pct: !input red_brightness_pct

  - delay:
      seconds: !input minute_step_secs

  # Minute 1 — Red-Orange @ 25%
  - service: light.turn_on
    target:
      entity_id: !input target_light
    data:
      hs_color:
        - !input orange_hue_deg
        - !input saturation_pct
      brightness_pct: 25

  - delay:
      seconds: !input minute_step_secs

  # Minute 2 — Yellow @ 50%
  - service: light.turn_on
    target:
      entity_id: !input target_light
    data:
      hs_color:
        - 60
        - !input saturation_pct
      brightness_pct: 50

  - delay:
      seconds: !input minute_step_secs

  # Minute 3 — Yellow-Green @ 75%
  - service: light.turn_on
    target:
      entity_id: !input target_light
    data:
      hs_color:
        - 90
        - !input saturation_pct
      brightness_pct: 75

  - delay:
      seconds: !input minute_step_secs

  # Minute 4 — Green @ target brightness
  - service: light.turn_on
    target:
      entity_id: !input target_light
    data:
      hs_color:
        - 120
        - !input saturation_pct
      brightness_pct: !input green_brightness_pct

  # Hold green for the configured duration
  - delay: !input green_hold_duration

  # Return to Red @ 1%
  - service: light.turn_on
    target:
      entity_id: !input target_light
    data:
      hs_color:
        - 0
        - !input saturation_pct
      brightness_pct: !input red_brightness_pct

  # Ensure the red state is applied before turning off
  - delay:
      seconds: !input post_red_settle_secs

  # Then off
  - service: light.turn_off
    target:
      entity_id: !input target_light
